import turtle

wn = turtle.Screen()
wn.setup(width = 400, height = 300)

cake = turtle.Turtle()
cake.speed(2)
cake.fillcolor("navajowhite")
cake.hideturtle()

cake.begin_fill()
cake.right(20)
cake.forward(100)
cake.right(70)
cake.forward(50)
cake.right(90)
cake.forward(120)
cake.right(90)
cake.forward(50)
cake.right(90)
cake.forward(120)
cake.penup()
cake.goto(0,0)
cake.pendown()
cake.right(125)
cake.forward(45)
cake.end_fill()
cake.setheading(270)

cake.fillcolor("salmon")
cake.begin_fill()
cake.forward(20)
cake.left(90)
cake.forward(120)
cake.right(90)
cake.forward(5)
cake.right(90)
cake.forward(120)
cake.end_fill()
cake.penup()
cake.goto(-10,0)
cake.pendown()
cake.penup()
cake.goto(10, 0)
cake.pendown()

cake.fillcolor("firebrick")
cake.begin_fill()
cake.circle(10)
cake.end_fill()
